### PR TITLE
Powerset stream

### PR DESCRIPTION
**Pull request by brightcoder**
Generating pull request with source code and test cases. gradle build is successful for this.
@siordache Have a look at it when you get time.
I am planning to add documentation in user_guide.adoc in separate commit once we are good with these code changes.

### CODE REVIEW

**Comment by siordache** [comment]
Thanks! It looks great!

I suggest only a few cosmetic changes:
- In PowerSetSupplier, implement printArray() using a logger instead of System.out:

```
    private void printArray(int[] arr, String string) {
        if(logger.isTraceEnabled()) {
            logger.trace(string + ": " + Arrays.toString(arr));
        }
    }
```
- In BigIntegerPowerSet.powerOfTwo(), use shiftLeft instead of repeatedly multiplying:

```
    BigInteger power = BigInteger.ONE.shiftLeft(length);
```
- The javadoc of powerOfTwo() in LongPowerSet and BigIntegerPowerSet currently reads: `Calculates length ^ 2.`. It should be: `2 ^ length`.
- The javadoc of BigIntegerPowerSet currently reads: `For length <= 20, you may consider...`. It should be: `For length < 63`.

**Comment by brightcoder** [comment]
Updated the pull request with the following changes.
- Removed printArray method in PowerSetSupplier. I wrote it to debug my code. It is no longer needed.
- Updated java doc wherever needed.

Not sure why travis build is failing the check.

**Comment by siordache** [comment]
Travis is currently experiencing some problems. It has nothing to do with your code.

But I cannot see your changes. Did you push them?

**Comment by brightcoder** [comment]
I force pushed the changes. So same commit is updated with the new changes.

**Comment by siordache** [comment]
Yes, it looks good. Now you only have to add the documentation in user_guide.adoc and you're done.

**Comment by brightcoder** [comment]
Updated the commit by adding documentation of PowerSet stream in user_guide.adoc.

**Comment by siordache** [comment]
Thanks @brightcoder, great work!
And congratulations! You've made your first open-source contribution.

**Comment by siordache** [comment]
I just noticed that you didn't use your @brightcoder account to push the changes.
Therefore you don't show up in the list of contributors.
That's a shame, because you did an excellent job.

**Comment by brightcoder** [comment]
Hard luck. Not sure how did I miss it but no issues. 👍

**Pull request merged**
